"""empty message

Revision ID: 405a27d0ed26
Revises: 2db76820d841
Create Date: 2022-09-22 04:37:13.289394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '405a27d0ed26'
down_revision = '2db76820d841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Dog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ride')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ride',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ride_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Ride_user_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Dog.id'], name='Ride_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Ride_pkey')
    )
    op.drop_table('Duty')
    # ### end Alembic commands ###
