"""empty message

Revision ID: 41abf893387e
Revises: 71005446b1b2
Create Date: 2022-09-22 04:04:41.627826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41abf893387e'
down_revision = '71005446b1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('User', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('lastname', sa.String(), nullable=True))
    op.drop_column('User', 'state')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('User', 'lastname')
    op.drop_column('User', 'firstname')
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
