"""empty message

Revision ID: a4c9cba14570
Revises: 405a27d0ed26
Create Date: 2022-09-22 05:37:18.102377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c9cba14570'
down_revision = '405a27d0ed26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Duty', sa.Column('dog_id_id', sa.Integer(), nullable=True))
    op.drop_constraint('Duty_venue_id_fkey', 'Duty', type_='foreignkey')
    op.create_foreign_key(None, 'Duty', 'Dog', ['dog_id_id'], ['id'])
    op.drop_column('Duty', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Duty', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Duty', type_='foreignkey')
    op.create_foreign_key('Duty_venue_id_fkey', 'Duty', 'Dog', ['venue_id'], ['id'])
    op.drop_column('Duty', 'dog_id_id')
    # ### end Alembic commands ###
